# Generated by Django 2.2.5 on 2020-07-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='district',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='district',
            field=models.ManyToManyField(related_name='restaurant', to='food.District'),
        ),
    ]
