# Generated by Django 2.2.5 on 2020-07-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_dishes_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='img',
            field=models.ImageField(null=True, upload_to='static/imgs'),
        ),
    ]
