# Generated by Django 2.2.5 on 2020-08-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_dishes_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(null=True, upload_to='static/logos'),
        ),
    ]
