# Generated by Django 2.2.5 on 2020-08-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20200804_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saludinst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo', models.ImageField(null=True, upload_to='static/logos')),
                ('description', models.TextField()),
                ('category', models.ManyToManyField(related_name='saludinst', to='food.Category')),
                ('district', models.ManyToManyField(related_name='saludinst', to='food.District')),
            ],
        ),
    ]
