# Generated by Django 2.2.5 on 2021-01-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_saludinst_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
