# Generated by Django 2.2.5 on 2021-01-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20210118_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='img',
            field=models.ImageField(blank=True, default='static/imgs/food_default.jpg', null=True, upload_to='static/imgs'),
        ),
    ]
