# Generated by Django 2.2.5 on 2021-01-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20210118_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesOfFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('restaurant', models.ManyToManyField(related_name='typeoffood', to='food.Dishes')),
            ],
        ),
    ]
