# Generated by Django 2.2.5 on 2021-01-18 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_typesoffood'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='dishes',
            name='typeof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeof', to='food.TypeOf'),
        ),
    ]
