# Generated by Django 2.2.5 on 2021-01-18 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20210118_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='typeof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='food.TypeOf'),
        ),
    ]
