# Generated by Django 2.2.5 on 2021-01-19 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_auto_20210118_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='food.Restaurant'),
        ),
    ]
