# Generated by Django 2.2.5 on 2021-01-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_dishes_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='restaurant',
        ),
    ]
