# Generated by Django 2.2.5 on 2021-01-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_typeof_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeof',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
