# Generated by Django 2.2.5 on 2021-01-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_auto_20210119_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='url',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
