# Generated by Django 2.2.5 on 2021-01-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_restaurant_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeof',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
