# Generated by Django 2.2.5 on 2021-01-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_typeof_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
