# Generated by Django 2.2.5 on 2021-02-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_restaurant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('published', models.BooleanField(default=False)),
                ('logo', models.ImageField(null=True, upload_to='static/logos')),
                ('url', models.CharField(blank=True, max_length=64)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('category', models.ManyToManyField(related_name='store', to='food.Category')),
                ('district', models.ManyToManyField(related_name='store', to='food.District')),
            ],
        ),
    ]
