# Generated by Django 2.2.5 on 2021-02-05 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0023_auto_20210205_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Storesubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Storesubcategory', to='food.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('published', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, default='static/imgs/article_default.jpg', null=True, upload_to='static/imgs')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typeof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='food.Storesubcategory')),
            ],
        ),
    ]
