# Generated by Django 2.2.5 on 2021-02-05 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0024_auto_20210205_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesubcategory',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storesubcategory', to='food.Store'),
        ),
    ]
