# Generated by Django 2.2.5 on 2021-02-05 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0025_auto_20210205_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='typeof',
            new_name='storesubcategory',
        ),
    ]
