# Generated by Django 2.2.5 on 2021-02-05 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0026_auto_20210205_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='storesubcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='food.Storesubcategory'),
        ),
    ]
