# Generated by Django 2.2.5 on 2021-02-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0027_auto_20210205_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
